import numpy as np
from workflow import create_model, run_solver, run_analysis
from musiq.workflow.contracts import AnalyserConfig, SolverConfig, TaskConfig, TaskInputConfig, WorkflowOutputOptions, DeviceConfig, PulseConfig, WorkflowRunOptions
from musiq.schemas.utils import ParameterList, ParameterSweepConfig

def test_parametric_analysis():
    print("Starting Smoke Test: Parametric Analysis...")

    # 1. Setup minimal Model manually
    from musiq.workflow.model import Model, ModelConfig
    
    task_cfg = TaskConfig(
        target="rabi",
        input=TaskInputConfig(
            qasm_text="OPENQASM 3; qubit[1] q; x q[0];",
            solver_config_path=None,
            device_config_path=None,
            pulse_config_path=None,
            analyser_config_path=None,
            param_bindings={}
        ),
        output=WorkflowOutputOptions(out_dir="dev/smoke_out"),
    )
    
    solver_cfg = SolverConfig(
        run=WorkflowRunOptions(solver_mode="se", engine="mock"),
        study=[{
            "name": "sweep_amp",
            "parameters": {
                "amp": ParameterList(target="amp", values=[0.1, 0.2, 0.3, 0.4, 0.5], unit="V")
            }
        }]
    )
    
    analyser_cfg = AnalyserConfig(
        solver_id="solver_0",
        metrics=["population", "leakage"],
        parametric_metrics=["final_population", "final_leakage"]
    )

    config = ModelConfig(
        tasks={"rabi": task_cfg},
        devices={"dev_0": DeviceConfig(device={}, pulse={}, noise={})},
        pulses={"pulse_0": PulseConfig(acquisition={}, timing={}, channels={}, extras={})},
        solvers={"solver_0": solver_cfg},
        analysers={"analyser_0": analyser_cfg}
    )
    
    model = Model(config=config)
    
    # In this smoke test, we rely on the first item in ModelConfig for defaults
    # which is how the Model properties (task, device, pulse) are implemented.
    
    # Set the parameter list globally for the model
    model.config.parameter_list = ParameterSweepConfig(
        parameters={
            "amp": ParameterList(target="amp", values=[0.1, 0.2, 0.3, 0.4, 0.5], unit="V")
        }
    )

    try:
        print("Manually populating mock solver results for analysis test...")
        from musiq.schemas.model import ModelRun, RunIdentity, RunStatus, RunArtifacts, ModelSpec
        from musiq.schemas.results import RunResult, RunProvenance, Trajectory
        from musiq.workflow.contracts import compose_workflow_task
        
        # Create a real Task contract to satisfy run_analysis requirements
        runtime_task = compose_workflow_task(
            task_cfg=config.tasks["rabi"],
            solver_cfg=config.solvers["solver_0"],
            device_cfg=config.devices["dev_0"],
            analyser_cfg=config.analysers["analyser_0"],
            model_pulse=config.pulses["pulse_0"]
        )

        # Create a mock run
        run_id = "run_0"
        model_run = ModelRun(
            identity=RunIdentity(run_id=run_id, solver_id="solver_0"),
            runtime_task=runtime_task,
            status=RunStatus.COMPLETED,
            artifacts=RunArtifacts(model_spec=ModelSpec()),
            results={}
        )
        
        # Populate results for each parameter point (5 points from amp sweep)
        # Use the same IDs that would be generated by the workflow
        param_values = [0.1, 0.2, 0.3, 0.4, 0.5]
        for i, val in enumerate(param_values):
            param_id = f"p{i}"
            # Mock a RunResult with some trajectories
            # Each Trajectory needs a 'measurements' or similar to get population
            # The actual analysis logic looks for 'population' in trajectory.measurements
            
            # Creating a dummy trajectory with population and leakage
            trajectory = Trajectory(
                times=[0.0],
                measurements={
                    "population": np.random.rand(),
                    "leakage": np.random.rand() * 0.1
                }
            )
            
            model_run.results[param_id] = RunResult(
                result_id=f"res_{param_id}",
                parameters={"amp": val},
                trajectories={"traj_0": trajectory},
                provenance=RunProvenance(solver_id="solver_0")
            )
            
        model.runs[run_id] = model_run
        
        # We need to make sure the analyser knows which run to look at
        # Normally this is handled by the workflow, but we'll set the last_run_id
        model.state.last_run_id = run_id

        print("Running analysis...")
        run_analysis(model, analyser_id="analyser_0")
        
        print("\n--- Analysis Results ---")
        print(f"Analyses keys: {list(model.analyses.keys())}")
        
        # Check for parametric analysis
        if "analyser_0" in model.analyses:
            analysis = model.analyses["analyser_0"]
            print(f"Main analysis scope: {analysis.scope}")
            
            if analysis.scope.value == "parametric":
                out = analysis.output
                print(f"Parametric Parameters: {list(out.parameters.keys())}")
                print(f"Parametric Metrics: {list(out.metrics.keys())}")
                
                for m_name, m_val in out.metrics.items():
                    print(f"Metric {m_name}: dimensions={m_val.dimensions}, values_len={len(m_val.values)}")
                    assert len(m_val.values) == 5, f"Expected 5 values for {m_name}, got {len(m_val.values)}"
            else:
                print(f"Unexpected scope: {analysis.scope}")
        else:
            print("Error: analyser_0 not found in model.analyses")

        print("\nSmoke test PASSED!")

    except Exception as e:
        import traceback
        traceback.print_exc()
        print("\nSmoke test FAILED!")
        raise e

if __name__ == "__main__":
    test_parametric_analysis()